Renting_Django_Project/capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rental.urls', namespace='rental'))
]

Renting_Django_Project/capstone/rental/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'rental'

urlpatterns = [
    path("", views.redirect_to_main, name="index"),
    path("main", views.index, name="main"),
    path("ad-<int:ad_id>", views.index, name="open-ad"),
    path("create", views.create_ad, name="create"),
    path("edit/<int:ad_id>", views.edit_ad, name="edit"),
    path("profile", views.profile, name="profile"),
    path("profile-<str:section>", views.profile, name="profile-section"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # For use by JS fetch functions:
    path("index/message/<int:ad_id>", views.start_dialog, name="start_dialog"),
    path("ad/<int:ad_id>", views.load_ad, name="load_ad"),
    path("ad/is_saved/<int:ad_id>", views.is_saved, name="is_saved"),
    path("ad/save/<int:ad_id>", views.to_saved, name="save_ad"),
    path("ad/activate/<int:ad_id>", views.change_active, name="change_active"),
    path("profile/load_ads", views.profile_load_ads, name="profile_load_ads"),
    path("profile/load_saved", views.profile_load_saved, name="profile_load_saved"),
    path("profile/dialogs", views.load_dialogs, name="load_dialogs"),
    path("profile/dialog/<int:dialog_id>", views.load_dialog, name="load_dialog"),
    path("profile/message/<int:dialog_id>", views.send_message, name="send_message"),
    path("profile/update", views.update_profile, name="profile_update"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Renting_Django_Project/capstone/rental/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.core.validators import MinValueValidator, FileExtensionValidator
from django.utils import timezone


def validate_date(value):
    """Validate if date is not earlier than current"""
    if value < timezone.now().date():
        raise ValidationError("The chosen date must be today or later",
                              code="min_value")


class User(AbstractUser):
    mobile_phone = models.CharField(max_length=20, blank=True, null=True)
    saved = models.ManyToManyField("Ad", blank=True, related_name="saved_by")


class Ad(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="user_ad")
    city = models.CharField(max_length=32)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=8, decimal_places=2,
                                validators=[MinValueValidator(1)])
    furniture = models.BooleanField(default=False)
    rooms = models.IntegerField(validators=[MinValueValidator(1)])
    available_now = models.BooleanField(default=True)
    available_from = models.DateField(default=None, null=True, blank=True,
                                      validators=[validate_date])
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(default=None, null=True, blank=True)
    is_actual = models.BooleanField(default=True)
    image = models.ImageField(default=None, null=True, blank=True,
                              upload_to="ad_images",
                              validators=[FileExtensionValidator(
                                  ['jpg', 'jpeg', 'png', 'gif'])])

    def __str__(self):
        return f"{self.id} {self.user}, {self.city}, active={self.is_actual}"


class Dialog(models.Model):
    initiator = models.ForeignKey(User, on_delete=models.CASCADE,
                                  related_name="initiated_dialogs")
    recipient = models.ForeignKey(User, on_delete=models.CASCADE,
                                  related_name="received_dialogs")
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE,
                           related_name="related_dialogs")
    creation_date = models.DateTimeField(auto_now_add=True)
    initiator_read = models.BooleanField(default=True)
    recipient_read = models.BooleanField(default=False)

    def clean(self):
        if self.initiator == self.ad.user:
            raise ValidationError("The initiator cannot be the author of the ad.")
        if self.initiator == self.recipient:
            raise ValidationError("The initiator and recipient cannot be the same user.")

    class Meta:
        unique_together = ('initiator', 'recipient', 'ad')

    def __str__(self):
        return f"{self.initiator} : {self.recipient} on ({self.ad})"


class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="user_message", null=True,
                               blank=True)
    dialog = models.ForeignKey(Dialog, on_delete=models.CASCADE,
                               related_name="dialog_messages", null=True,
                               blank=True)
    text = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} on dialog ({self.dialog}). {self.creation_date}"

Renting_Django_Project/capstone/rental/forms.py
from django import forms
from .models import Message, Ad


class NewMessage(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("text",)
        widgets = {
            "text": forms.Textarea(attrs={
                "placeholder": "Enter message",
                "class": "message-textarea",
                "rows": 4,
                "cols": 40,
            }),
        }
        labels = {
            "text": "New message"
        }


class NewAd(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data["available_now"] and \
                not cleaned_data.get("available_from"):
            self.add_error("available_from", "Date field is mandatory if "
                                             "not available now")
        elif cleaned_data["available_now"]:
            cleaned_data["available_from"] = None

    def clean_title(self):
        value: str = self.cleaned_data['title']
        return value.title()

    def clean_city(self):
        value: str = self.cleaned_data['city']
        return value.title()

    class Meta:
        model = Ad
        fields = ("title", "city", "description", "price",
                  "furniture", "rooms", "available_now",
                  "available_from", "image")
        widgets = {
            "description": forms.Textarea(attrs={
                "placeholder": "Enter description",
                "class": "message-textarea",
                "rows": 4,
                "cols": 20,
            }),
            "available_from": forms.DateInput(format='%d/%m/%Y',
                                              attrs={'type': 'date'})
        }
        labels = {
            "description": "Description"
        }
        error_messages = {
            'price': {
                'min_value': "Price cannot be less than 1.00$",
            },
            'rooms': {
                'min_value': "Number of rooms cannot be less then 1",
            }
        }

Renting_Django_Project/capstone/rental/views.py
import json
import re
from datetime import datetime
from decimal import Decimal

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.db.models import Max
from django.http import HttpResponseRedirect, JsonResponse, \
    HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from .models import User, Ad, Message, Dialog
from .forms import NewMessage, NewAd


def read_dialog(request, dialog_object, action: str):
    """
    Change dialog's "read" status depending on user "action".
    "action" is a string: "read" or "send".
    Is used in the load_dialog(), star_dialogs(), send_message().
    """
    if action == "read":
        if request.user == dialog_object.recipient:
            dialog_object.recipient_read = True
        else:
            dialog_object.initiator_read = True
    if action == "send":
        if request.user == dialog_object.recipient:
            dialog_object.initiator_read = False
        else:
            dialog_object.recipient_read = False
    dialog_object.save()


def pagination(request, post_list, num_pages=8):
    paginator = Paginator(post_list, num_pages)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return page_obj


def redirect_to_main(request):
    return redirect("rental:main")


def filter_ads(parameters: dict) -> set:
    """
    Parameters - dict of GET parameters passed in the URL.
    Is used in the index() function.
    Returns QuerySet of Ad model objects.
    """
    city = parameters.get('city', 'all').strip().title()
    city_filter = {} if city == '' else {'city': city}
    pricefrom = parameters.get('pricefrom', 0)
    pricefrom = Decimal(0) if pricefrom == '' else pricefrom
    priceto = parameters.get('priceto', 1_000_000)
    priceto = Decimal(1_000_000) if priceto == '' else priceto
    rooms = int(parameters.get('rooms', 0))
    furniture = int(parameters.get('furniture', -1))

    # Exclude filtering by rooms if rooms parameter is set to 0.
    if rooms == 0 or rooms == 4:
        rooms_filter = {'rooms__gte': rooms}
    else:
        rooms_filter = {'rooms': rooms}

    # Exclude filtering by furniture if furniture parameter is None
    if furniture == 1:
        furniture_filter = {
            'furniture': True  # Filter for the specified furniture value
        }
    elif furniture == 0:
        furniture_filter = {
            'furniture': False
        }
    else:
        furniture_filter = {}

    ads = Ad.objects.filter(
        **city_filter,
        price__range=(pricefrom, priceto),
        **rooms_filter,
        **furniture_filter,
        is_actual=True  # Doesn't show archived ads on main page.
    )
    return ads


def sorting_ads(ads_set, sorting_method):
    """
    Order ads depending on sorting_method.
    Is used in the index() function.
    """
    if sorting_method == "price_desc":
        post_list = ads_set.order_by("-price")
        sorting = "Price - High to Low"
    elif sorting_method == "price_asc":
        post_list = ads_set.order_by("price")
        sorting = "Price - Low to High"
    else:   # If "newest" or any unrecognized sorting method.
        post_list = ads_set.order_by("-creation_date")
        sorting = "Creation - Newest"
    return post_list, sorting


def index(request, ad_id=0):
    """
    ad_id is used in case if particular ad is opened as first page. This
    parameter is used by JS fetch function to dynamically load ad.
    """
    is_filtered = request.GET.get("filter", False)  # Check if filter was applied.
    if is_filtered:
        ads = filter_ads(request.GET)
    else:
        ads = Ad.objects.filter(is_actual=True)

    sorting = request.GET.get("sorting", "newest")
    post_list, sorting = sorting_ads(ads, sorting)
    page_obj = pagination(request, post_list)

    # get_params is used with pagination. Preserve GET parameters when change page.
    get_params = ""
    for key, value in request.GET.items():
        if key != 'page':
            get_params += f"&{key}={value}"

    return render(request, "rental/index.html", {
        "page_obj": page_obj,
        "sorting": sorting,
        "get_params": get_params,
        "ad_id": ad_id
    })


@login_required
def create_ad(request):
    if request.method == 'POST':
        form = NewAd(request.POST, request.FILES)
        if form.is_valid():
            ad = form.save(commit=False)
            ad.user = request.user
            ad.save()
            return HttpResponseRedirect(reverse('rental:main'))
        else:
            return render(request, 'rental/create.html', {'form': form})
    else:
        form = NewAd()
    return render(request, 'rental/create.html', {'form': form})


@login_required
def edit_ad(request, ad_id):
    ad = get_object_or_404(Ad, id=ad_id)
    if request.user != ad.user:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = NewAd(request.POST, request.FILES, instance=ad)
        if form.is_valid():
            # Update only if any data was changed.
            if form.changed_data:
                ad = form.save(commit=False)
                ad.update_date = datetime.now()
                form.save()
            return HttpResponseRedirect(reverse('rental:main'))
    else:
        form = NewAd(instance=ad)
    return render(request, 'rental/create.html', {
        'form': form,
        'edit': True,  # To change form action on create.html page.
        'ad_id': ad_id
    })


@login_required
def profile(request, section=None):
    """Load profile page."""
    new_message = NewMessage()  # Is used at dialog page.
    return render(request, "rental/profile.html", {
        "new_message": new_message,
        "section": section
    })


@login_required
def profile_load_ads(request):
    """Dynamically load user's ads to the profile page."""
    ads = Ad.objects.filter(user=request.user).order_by("-creation_date")
    if not ads:
        json_response = None
    else:
        json_response = []
        for ad in ads:
            json_ad = {"id": ad.id, "city": ad.city, "title": ad.title,
                       "price": ad.price, "description": ad.description,
                       "isactive": ad.is_actual, "creation_date": ad.creation_date.strftime("%Y-%m-%d %H:%M")}
            json_response.append(json_ad)
    return JsonResponse(json_response, safe=False)


@login_required
def profile_load_saved(request):
    """Dynamically load to the profile page ads saved by user."""
    saved_ads = request.user.saved.all()
    if not saved_ads:
        json_response = None
    else:
        json_response = []
        for ad in saved_ads:
            json_ad = {"id": ad.id, "city": ad.city, "title": ad.title,
                       "price": ad.price, "description": ad.description,
                       "isactive": ad.is_actual, "creation_date":
                           ad.creation_date.strftime("%Y-%m-%d %H:%M")}
            json_response.append(json_ad)
    return JsonResponse(json_response, safe=False)


@login_required
def load_dialogs(request):
    """Dynamically load to the profile page user's dialogs."""
    dialogs = (Dialog.objects.filter(initiator=request.user) |
               Dialog.objects.filter(recipient=request.user))

    # Create field last_message_date for further ordering by it
    # depending on last message sent.
    dialogs = dialogs.annotate(
        last_message_date=Max('dialog_messages__creation_date'))
    dialogs = dialogs.order_by('-last_message_date')

    if not dialogs:
        json_response = None
    else:
        json_response = []
        for dialog in dialogs:
            if dialog.recipient == request.user:
                user = dialog.initiator.username
                read = dialog.recipient_read  # Indicates if it is new not yet read message.
            else:
                user = dialog.recipient.username
                read = dialog.initiator_read
            lst_msg = dialog.dialog_messages.order_by("-creation_date")[0]
            lst_msg_date = lst_msg.creation_date.strftime("%Y-%m-%d %H:%M")
            json_message = {"id": dialog.id, "ad_title": dialog.ad.title,
                            "user": user, "ad_city": dialog.ad.city,
                            "ad_price": dialog.ad.price,
                            "last_message_text": lst_msg.text,
                            "last_message_date": lst_msg_date,
                            "is_read": read
                            }
            json_response.append(json_message)
    return JsonResponse(json_response, safe=False)


@login_required
def load_dialog(request, dialog_id):
    dialog = get_object_or_404(Dialog, id=dialog_id)

    # Checks if requested user is one of the dialog's participant.
    if request.user != dialog.initiator and request.user != dialog.recipient:
        return HttpResponseForbidden()

    messages = dialog.dialog_messages.all().order_by("creation_date")
    # Mark all messages as "read" when load dialog:
    read_dialog(request, dialog, "read")
    json_messages = []
    for message in messages:
        json_messages.append({"author": message.author.username,
                              "text": message.text,
                              "datetime": message.creation_date.strftime("%Y-%m-%d %H:%M")})
    json_response = {"id": dialog.id, "ad_title": dialog.ad.title,
                     "ad_city": dialog.ad.city, "ad_price": dialog.ad.price,
                     "messages": json_messages}
    return JsonResponse(json_response, safe=False)


@login_required
def start_dialog(request, ad_id):
    """
    Dynamically create dialog/send message on the ad page with the
    author of the ad.
    """
    if request.method == "POST":

Renting_Django_Project/capstone/rental/templates/rental/create.html
{% extends "rental/layout.html" %}

{% load static %}
{% block script %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            let city = document.querySelector('#id_city');
            console.log(city);
            city.setAttribute('list', 'cities');

            let parent = city.parentNode;
            let datalist = document.createElement('datalist');
            datalist.id = 'cities';
            parent.appendChild(datalist);

            // Function implemented in the layout.js file.
            getCities("united states").then(data => {
                const cities = data;
                console.log(data);

                let datalist = document.querySelector("#cities");
                // Add each city as an option
                cities.forEach(city => {
                    const option = document.createElement('option');
                    option.value = city;
                    datalist.appendChild(option);
                });
            });
        });
    </script>
{% endblock %}

{% block style %}
{% endblock %}

{% block body %}
    <div id="create-form">
        <h5>Create New Ad</h5>
        <form id=ad-form method="post" enctype="multipart/form-data" action={% if edit %}"{% url 'rental:edit' ad_id %}"{% else %}"{% url 'rental:create' %}"{% endif %}>
            {% csrf_token %}
            <table>
            {{ form.as_table }}
                <tr>
                    <th><label for="submit-form"></label></th>
                    <td style="display: flex; justify-content: flex-end;">
                        <input id="submit-form" type="submit" value="Submit" class="btn btn-secondary">
                    </td>
                  </tr>
            </table>

        </form>
    </div>

{% endblock %}

Renting_Django_Project/capstone/rental/templates/rental/filter.html
<h5 id="filter-title">Filters:</h5>
<form id="filter-form" action="{% url 'rental:main' %}">

    {% if 'sorting' in request.GET %} {# Preserve sorting parameter #}
        <input type="hidden" name="sorting" value="{{ request.GET.sorting }}">
    {% endif %}

    <input type="hidden" name="filter" value="true">

    <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">City</span>
        </div>
        <input name="city" class="form-control" list="cities" placeholder="All cities"
                {% if 'filter' in request.GET %}
                    {% if request.GET.city %}
                    value="{{ request.GET.city.capitalize }}"
                    {% endif %}
                {% endif %}
        >
        <datalist id="cities">
        </datalist>
    </div>

    <div class="option">
        <label for="rooms" class="label">Rooms:</label>
        <select id="rooms" name="rooms">
            <option value="0" {% if 'filter' in request.GET and request.GET.rooms == "0" %} selected {% endif %}>All</option>
            {% for num in "123" %}
                <option value="{{ num }}" {% if 'filter' in request.GET and request.GET.rooms == num %} selected {% endif %}>{{ num }}</option>
            {% endfor %}
            <option value="4" {% if 'filter' in request.GET and request.GET.rooms == "4" %} selected {% endif %}>4 and more</option>
        </select>
    </div>

    <div class="option">
        <label for="pricefrom" class="label">Price from:</label>
        <input id="pricefrom" type="text" name="pricefrom" placeholder="0.00"
        {% if 'filter' in request.GET %}
            {% if request.GET.pricefrom %}
            value="{{ request.GET.pricefrom }}"
            {% endif %}
        {% endif %}>
        <label for="priceto" class="label">Price to:</label>
        <input id="priceto" type="text" name="priceto" placeholder="10000.00"
        {% if 'filter' in request.GET %}
            {% if request.GET.priceto %}
            value="{{ request.GET.priceto }}"
            {% endif %}
        {% endif %}>
    </div>

    <div class="option">
        <label for="furniture" class="label">Furniture:</label>
        <select id="furniture" name="furniture">
            <option value="-1" {% if 'filter' in request.GET and request.GET.furniture == "-1" %} selected {% endif %}>All</option>
            <option value="1" {% if 'filter' in request.GET and request.GET.furniture == "1" %} selected {% endif %}>Yes</option>
            <option value="0" {% if 'filter' in request.GET and request.GET.furniture == "0" %} selected {% endif %}>No</option>
        </select>
    </div>

    <button id="filter-apply" type="submit" class="btn btn-secondary btn-sm">Apply</button>
</form>

Renting_Django_Project/capstone/rental/templates/rental/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>USRental</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link href="{% static 'rental/styles.css' %}" rel="stylesheet">
        <script src="{% static 'rental/layout.js' %}"></script>
        {% block script %}
        {% endblock %}
        {% block style %}
        {% endblock %}
    </head>
    <body>
        <div class="navbar-container">
            <nav class="navbar navbar-expand-sm navbar-light">
                <a id="main-title" class="navbar-brand" href="{% url 'rental:main' %}">USRental</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="collapsibleNavbar" class="collapse navbar-collapse">
                  <ul class="navbar-nav mr-auto">
                        <li id="my-profile" class="nav-item">
                            <div class="dropdown show">
                                {% if user.is_authenticated %}
                                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <strong>{{ user.username }}</strong>
                                </a>
                                {% else %}
                                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <strong>My profile</strong>
                                </a>
                                {% endif %}
                                <div class="dropdown-menu" aria-labelledby="dropdownProfile">
                                    {% if user.is_authenticated %}
                                    <a class="dropdown-item" href="{% url 'rental:profile' %}">My profile</a>
                                    <a class="dropdown-item" href="{% url 'rental:logout' %}">Log out</a>
                                    {% else %}
                                    <a class="dropdown-item" href="{% url 'rental:login' %}">Log in</a>
                                    <a class="dropdown-item" href="{% url 'rental:register' %}">Register</a>
                                    {% endif %}
                                </div>
                            </div>
                        </li>
                    <li class="nav-item">
                      <a id="all-ads" class="nav-link" href="{% url 'rental:main' %}">All ads</a>
                    </li>
                    <li class="nav-item">
                      <a id="create-ad" class="nav-link" href="{% url 'rental:create' %}">Create ad</a>
                    </li>
                  </ul>
                </div>
            </nav>
        </div>
            {% block body %}
            {% endblock %}
    </body>
</html>

Renting_Django_Project/capstone/rental/templates/rental/login.html
{% extends "rental/layout.html" %}

{% block body %}

    <div id="login-page">
    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'rental:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'rental:register' %}">Register here.</a>
    </div>
{% endblock %}

Renting_Django_Project/capstone/rental/templates/rental/pagination.html
<nav class="page-pagination">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ get_params }}" aria-label="Previous">
            <span aria-hidden="true">&laquo; Prev</span>
          </a>
        </li>
        {% endif %}
        <li class="page-item disabled">
            <a class="page-link">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}{{ get_params }}" aria-label="Next">
            <span aria-hidden="true">Next &raquo;</span>
          </a>
        </li>
        {% endif %}
      </ul>
</nav>

Renting_Django_Project/capstone/rental/templates/rental/register.html
{% extends "rental/layout.html" %}

{% block body %}
    <div id="register-page">
    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'rental:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username" required>
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address" required>
        </div>
        <div class="form-group">
             <input type="tel" id="phone" class="form-control" name="phone" pattern="^\([0-9]{3}\) ?[0-9]{3}-[0-9]{4}\b$" placeholder="Phone number (NNN) NNN-NNNN" required>
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password" required>
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password" required>
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'rental:login' %}">Log In here.</a>
    </div>
{% endblock %}